# Github workflow to deploy the documentation to Github Pages

name: Deploy docs

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci

      - name: Build docs bundle
        run: npm run build

      - name: Deploy the website to the master branch
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m "Deploy docs"
          git push -f git@github.com:mojs/mojs.github.io.git master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
