# Github workflow to deploy the documentation to Github Pages

name: Deploy docs

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Build docs bundle
        run: npm run build

      - name: Deploy the documentation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        env:
          branch: master
          folder: docs/.vuepress/dist
